version: 0.1
log:
  level: debug
  fields:
    service: disco
    environment: development
storage:
  ipfs:
    # url: http://localhost:5001 # this is for working with single IPFS node
    router:
      nodes:
        - url: http://localhost:5001
        # - url: http://other.url
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: false
http:
  addr: :5000
  debug:
    addr: :5050
    prometheus:
      enabled: true
      path: /metrics
  headers:
    X-Content-Type-Options: [nosniff]
